[package]
name = "minimal"
version = "0.1.0"
edition = "2021"

[dependencies]
cogrs-callbacks = { path = "../../cogrs-callbacks" }
anyhow = "1.0.95"
serde_json = "1.0.138"

[lib]
crate-type = ["cdylib"]